# Download release packages from lastest id-dast build
# Publish to distribution releases

resources:
  pipelines:
  - pipeline: IDDast  # Name of the pipeline resource
    source: id-dast  # Name of the pipeline referenced by the pipeline resource

jobs:
- job: Publish
  pool:
    vmImage: ubuntu-latest

  steps:
    - download: IDDast
      artifact: linux
      patterns: "*.deb"
      displayName: 'Download IDDast Debian Artifact'
    - download: IDDast
      artifact: darwin
      patterns: "*.pkg"
      displayName: 'Download IDDast macOS Artifact'
    - download: IDDast
      artifact: windows
      patterns: "*.msi"
      displayName: 'Download IDDast Windows Artifact'
    - bash: |
        thisFile=$(ls *.deb)
        GIT_TAG=$(dpkg --info $thisFile | grep 'Version:' | sed 's/\WVersion:\W/v/g')
        echo "##vso[task.setvariable variable=GIT_TAG]$GIT_TAG"
        echo "Tag is ${GIT_TAG}"
      workingDirectory: $(Pipeline.Workspace)/IDDast/linux
      displayName: 'Generate Tag'
    - task: GitHubRelease@1
      displayName: 'Push to Release folder'
      inputs:
        gitHubConnection: github.com
        repositoryName: whitehatsec-innovations/distribution
        action: create
        tagSource: userSpecifiedTag
        target: $(Build.SourceVersion)
        tag: $(GIT_TAG)
        title: Release $(GIT_TAG)
        addChangeLog: false
        isPreRelease: false
        assetUploadMode: replace
        assets: |
          $(Pipeline.Workspace)/IDDast/darwin/*
          $(Pipeline.Workspace)/IDDast/linux/*
          $(Pipeline.Workspace)/IDDast/windows/*
